// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// WH_DYNAMIC_IV
Eigen::VectorXd WH_DYNAMIC_IV(std::string name, double n_max, double p_arm0surv, double p_arm1surv, double t_surv, double p_arm0tox1, double p_arm1tox1, double p_arm0tox2, double p_arm1tox2, double p_LTFU, double t_LTFU, double recrate, double t_recmax, double t_add, double t_max, int reps, int seed, bool echo);
RcppExport SEXP _DYNAMIC_IV_WH_DYNAMIC_IV(SEXP nameSEXP, SEXP n_maxSEXP, SEXP p_arm0survSEXP, SEXP p_arm1survSEXP, SEXP t_survSEXP, SEXP p_arm0tox1SEXP, SEXP p_arm1tox1SEXP, SEXP p_arm0tox2SEXP, SEXP p_arm1tox2SEXP, SEXP p_LTFUSEXP, SEXP t_LTFUSEXP, SEXP recrateSEXP, SEXP t_recmaxSEXP, SEXP t_addSEXP, SEXP t_maxSEXP, SEXP repsSEXP, SEXP seedSEXP, SEXP echoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< double >::type n_max(n_maxSEXP);
    Rcpp::traits::input_parameter< double >::type p_arm0surv(p_arm0survSEXP);
    Rcpp::traits::input_parameter< double >::type p_arm1surv(p_arm1survSEXP);
    Rcpp::traits::input_parameter< double >::type t_surv(t_survSEXP);
    Rcpp::traits::input_parameter< double >::type p_arm0tox1(p_arm0tox1SEXP);
    Rcpp::traits::input_parameter< double >::type p_arm1tox1(p_arm1tox1SEXP);
    Rcpp::traits::input_parameter< double >::type p_arm0tox2(p_arm0tox2SEXP);
    Rcpp::traits::input_parameter< double >::type p_arm1tox2(p_arm1tox2SEXP);
    Rcpp::traits::input_parameter< double >::type p_LTFU(p_LTFUSEXP);
    Rcpp::traits::input_parameter< double >::type t_LTFU(t_LTFUSEXP);
    Rcpp::traits::input_parameter< double >::type recrate(recrateSEXP);
    Rcpp::traits::input_parameter< double >::type t_recmax(t_recmaxSEXP);
    Rcpp::traits::input_parameter< double >::type t_add(t_addSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type echo(echoSEXP);
    rcpp_result_gen = Rcpp::wrap(WH_DYNAMIC_IV(name, n_max, p_arm0surv, p_arm1surv, t_surv, p_arm0tox1, p_arm1tox1, p_arm0tox2, p_arm1tox2, p_LTFU, t_LTFU, recrate, t_recmax, t_add, t_max, reps, seed, echo));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DYNAMIC_IV_WH_DYNAMIC_IV", (DL_FUNC) &_DYNAMIC_IV_WH_DYNAMIC_IV, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_DYNAMIC_IV(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
