// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// WH_NIHR502533a
Eigen::VectorXd WH_NIHR502533a(std::string name, double n_target, double p_arm0surv, double p_arm1surv, double t_surv, double p_arm0tox1, double p_arm1tox1, double p_arm0tox2, double p_arm1tox2, double p_LTFU, double t_LTFU, double recrate, double t_recmax, double t_add, double t_max, int reps, int seed, bool echo);
RcppExport SEXP _NIHR502533_WH_NIHR502533a(SEXP nameSEXP, SEXP n_targetSEXP, SEXP p_arm0survSEXP, SEXP p_arm1survSEXP, SEXP t_survSEXP, SEXP p_arm0tox1SEXP, SEXP p_arm1tox1SEXP, SEXP p_arm0tox2SEXP, SEXP p_arm1tox2SEXP, SEXP p_LTFUSEXP, SEXP t_LTFUSEXP, SEXP recrateSEXP, SEXP t_recmaxSEXP, SEXP t_addSEXP, SEXP t_maxSEXP, SEXP repsSEXP, SEXP seedSEXP, SEXP echoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< double >::type n_target(n_targetSEXP);
    Rcpp::traits::input_parameter< double >::type p_arm0surv(p_arm0survSEXP);
    Rcpp::traits::input_parameter< double >::type p_arm1surv(p_arm1survSEXP);
    Rcpp::traits::input_parameter< double >::type t_surv(t_survSEXP);
    Rcpp::traits::input_parameter< double >::type p_arm0tox1(p_arm0tox1SEXP);
    Rcpp::traits::input_parameter< double >::type p_arm1tox1(p_arm1tox1SEXP);
    Rcpp::traits::input_parameter< double >::type p_arm0tox2(p_arm0tox2SEXP);
    Rcpp::traits::input_parameter< double >::type p_arm1tox2(p_arm1tox2SEXP);
    Rcpp::traits::input_parameter< double >::type p_LTFU(p_LTFUSEXP);
    Rcpp::traits::input_parameter< double >::type t_LTFU(t_LTFUSEXP);
    Rcpp::traits::input_parameter< double >::type recrate(recrateSEXP);
    Rcpp::traits::input_parameter< double >::type t_recmax(t_recmaxSEXP);
    Rcpp::traits::input_parameter< double >::type t_add(t_addSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type echo(echoSEXP);
    rcpp_result_gen = Rcpp::wrap(WH_NIHR502533a(name, n_target, p_arm0surv, p_arm1surv, t_surv, p_arm0tox1, p_arm1tox1, p_arm0tox2, p_arm1tox2, p_LTFU, t_LTFU, recrate, t_recmax, t_add, t_max, reps, seed, echo));
    return rcpp_result_gen;
END_RCPP
}
// WH_NIHR502533b
Eigen::VectorXd WH_NIHR502533b(std::string name, double n_target, const double p_nullclear, const double p_arm0clear, double t_surv, const double p_LTFU, const double t_LTFU, const double recrate, const double t_recmax, double t_add, double t_max, int reps, int seed);
RcppExport SEXP _NIHR502533_WH_NIHR502533b(SEXP nameSEXP, SEXP n_targetSEXP, SEXP p_nullclearSEXP, SEXP p_arm0clearSEXP, SEXP t_survSEXP, SEXP p_LTFUSEXP, SEXP t_LTFUSEXP, SEXP recrateSEXP, SEXP t_recmaxSEXP, SEXP t_addSEXP, SEXP t_maxSEXP, SEXP repsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< double >::type n_target(n_targetSEXP);
    Rcpp::traits::input_parameter< const double >::type p_nullclear(p_nullclearSEXP);
    Rcpp::traits::input_parameter< const double >::type p_arm0clear(p_arm0clearSEXP);
    Rcpp::traits::input_parameter< double >::type t_surv(t_survSEXP);
    Rcpp::traits::input_parameter< const double >::type p_LTFU(p_LTFUSEXP);
    Rcpp::traits::input_parameter< const double >::type t_LTFU(t_LTFUSEXP);
    Rcpp::traits::input_parameter< const double >::type recrate(recrateSEXP);
    Rcpp::traits::input_parameter< const double >::type t_recmax(t_recmaxSEXP);
    Rcpp::traits::input_parameter< double >::type t_add(t_addSEXP);
    Rcpp::traits::input_parameter< double >::type t_max(t_maxSEXP);
    Rcpp::traits::input_parameter< int >::type reps(repsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(WH_NIHR502533b(name, n_target, p_nullclear, p_arm0clear, t_surv, p_LTFU, t_LTFU, recrate, t_recmax, t_add, t_max, reps, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NIHR502533_WH_NIHR502533a", (DL_FUNC) &_NIHR502533_WH_NIHR502533a, 18},
    {"_NIHR502533_WH_NIHR502533b", (DL_FUNC) &_NIHR502533_WH_NIHR502533b, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_NIHR502533(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
