# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' DYNAMIC-IV cohort A
#'
#' Sample size simulator for DYNAMIC-IV cohort A.
#'
#' @param name Scenario label. Default = `"scenario 1"`.
#' @param n_max Maximum sample size. Default = `204`.
#' @param p_arm0surv Control arm recurrence-free survival probability at `t_surv`
#' months. Default = `0.73`.
#' @param p_arm1surv Experimental arm recurrence-free survival probability at
#' `t_surv` months. Default = `0.70`.
#' @param t_surv Time in months when survival is assessed. Default = `36`.
#' @param p_arm0tox1 Control arm probability of toxicity 1. Default = `0.24`.
#' @param p_arm1tox1 Experimental arm probability of toxicity 1. Default =
#' `0.10`.
#' @param p_arm0tox2 Control arm probability of toxicity 2. Default = `0.45`.
#' @param p_arm1tox2 Experimental arm probability of toxicity 2. Default =
#' `0.05`.
#' @param p_LTFU Average proportion lost to follow-up per `t_LTFU` months.
#' Default = `0.1`.
#' @param t_LTFU Duration in months over which `p_LTFU` are lost to follow-up.
#' Default = `60`.
#' @param recrate Average number of participants recruited per month. Default
#' = `7.5`.
#' @param t_recmax Maximum recruitment duration in months. Default = `60`.
#' @param t_add Months of additional follow-up after recruitment closes.
#' Default = `36`.
#' @param t_max Maximum trial duration in months. Default = `72`.
#' @param reps Number of simulation replicates. Default = `1e5`.
#' @param seed Random seed. Default = `24601`.
#' @param echo Logical value indicating whether to print scenario information.
#' Default = `TRUE`.
#' @return A numeric vector with 3 elements: mean sample size, power, and mean
#' trial duration in months.
#' @export
WH_DYNAMIC_IV <- function(name = "scenario 1", n_max = 204, p_arm0surv = 0.73, p_arm1surv = 0.70, t_surv = 36, p_arm0tox1 = 0.25, p_arm1tox1 = 0.1, p_arm0tox2 = 0.45, p_arm1tox2 = 0.05, p_LTFU = 0.1, t_LTFU = 60, recrate = 7.5, t_recmax = 60, t_add = 36, t_max = 72, reps = 1e5L, seed = 24601L, echo = TRUE) {
    .Call(`_DYNAMIC_IV_WH_DYNAMIC_IV`, name, n_max, p_arm0surv, p_arm1surv, t_surv, p_arm0tox1, p_arm1tox1, p_arm0tox2, p_arm1tox2, p_LTFU, t_LTFU, recrate, t_recmax, t_add, t_max, reps, seed, echo)
}

